### ISSUE TITLE
Backend started nd 

### ISSUE THREAD

**Issue by oberer-Twix** [Project-2022-23/Tauben#6]
# Report Issues

### Description of the Issue
The Problem is that the Backend.jar from the Docker-Compose won't start

### How do you think that the Issue can be fixed
The Issue may be fixed by changing the config of the jar

### How to reproduce the Issue
- `docker compose up --build`

### If usefull add a Screenshot here
```
taubenprojekt-backend-1   | no main manifest attribute, in backend-docker.jar
taubenprojekt-backend-1 exited with code 1
```

### What is the expected behaviour after the Issue is fixed?
it should start

**Comment by LuckeyLukey** [comment]
leicht
